-- New audit actions for the admin "Teachers & Classes" management page.
ALTER TYPE "AuditAction" ADD VALUE 'ACTIVITY_TEMPLATE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ACTIVITY_TEMPLATE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'TEACHER_CLASS_ASSIGNMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'TEACHER_CLASS_ASSIGNMENT_UPDATED';
